manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk_split_esb
      remote: zmkfirmware
      revision: main
      path: modules/zmk_split_esb
    - name: sdk-nrf
      remote: nrfconnect
      revision: v2.5-branch
      import:
        name-allowlist:
          - nrf
      path: nrf
    - name: sdk-nrfxlib
      remote: nrfconnect
      revision: v2.5-branch
      path: nrfxlib

  self:
    path: config
